### ISSUE TITLE
feelpp-toolboxes: Wrong CMAKE_BUILD_TYPE in focal 

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp.pkg#3]
@prudhomm  Could you change this line in debian/rules (present at least for focal):

 CMAKE_BUILD_TYPE=None

**Comment by prudhomm** [comment]
why?

**Comment by prudhomm** [comment]
Otherwise I get -g -O3 as option and it is killing memory and disk storage. 
If you tell me how to get rid of `-g` I will happily do that

**Comment by Trophime** [comment]
Actually I had the trouble when trying to rebuild feelpp-toolboxes on focal with pdebuild.
(NB: I just download the latest git rev.)
Maybe we can overwrite CFLAGS options with the standard CMAKE options?

With `CMAKE_BUILD_TYPE=Release`, I got some errors also like that:
```
-- [feelpp] /build/feelpp-toolboxes-0.108.0~alpha.2/benchmarks/benchmark: submodule hold!
CMake Error at benchmarks/CMakeLists.txt:48 (add_subdirectory):
  The source directory

    /build/feelpp-toolboxes-0.108.0~alpha.2/benchmarks/benchmark

  does not contain a CMakeLists.txt file.
```

What are the submodules you use for the build?

I also got error messages like that:
```
CMake Error: Could not open file for write in copy operation /nonexistent/feel/geo/test_twodomains.geo.tmp
```

**Comment by Trophime** [comment]
@prudhomm what compilation flag do you use: -O3 only or -g -O2?

**Comment by prudhomm** [comment]
I wish to have -O2 or -O3 but not - g. I haven't found a way to get rid of it. It generates huge builds and fill the disks for feelpp toolboxes. Most failures are due to disk full.

**Comment by prudhomm** [comment]
Otherwise i use pbuilder-dist. It works like a charm.

**Comment by Trophime** [comment]
@prudhomm There is something wicked.
In debian/rules you use: `-DFEELPP_TOOLBOXES_ENABLE`
but in feelpp/develop CMakeLists.txt : `OPTION(FEELPP_ENABLE_TOOLBOXES "enable Feel++ toolboxes" OFF)`

**Comment by prudhomm** [comment]
Why wicked? We don't want the toolboxes by default

**Comment by Trophime** [comment]
I meant that there is no FEELPP_TOOLBOXES_ENABLE... This is confusing.  IMO that shall be removed from extra-flags in feelpp-toolboxes debian/rules

Next I wonder if you use a specific source tarball for feelpp-toolboxes (containing only the toolboxes part) or just the plain feelpp tarbal with submodules.

**Comment by prudhomm** [comment]
regarding the first point the option ` -DFEELPP_ENABLE_TOOLBOXES=OFF ` for the feelpp package is there because in the tarball I haave all the code source including toolboxes and mor.  in feelppp-toolboxes, on the code in `toolboxes/` is archived. In that case ` -DFEELPP_ENABLE_TOOLBOXES=OFF ` is not relevant anymore.

regarding the second, the tarball is generated on the fly from the checkout in feelpp toolboxes thank to cpack.

see the script here for more details:
https://github.com/feelpp/feelpp/blob/develop/feelpp/tools/scripts/pkg/feelpp_pkg.sh.in

**Comment by Trophime** [comment]
Regarding the "-g" issue, I think I have made some progress.
I think we can overwrite cmake default compilation flags in debian/rules by using:
```
 -DCMAKE_C_FLAGS:STRING="-DNDEBUG -O2 -Wdate-time -D_FORTIFY_SOURCE=2 " \
 -DCMAKE_C_FLAGS_DEBUG:STRING="" \
 -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG -O3" \
 -DCMAKE_CXX_FLAGS:STRING="-DNDEBUG -O2 -Wdate-time -D_FORTIFY_SOURCE=2 " \
 -DCMAKE_CXX_FLAGS_DEBUG:STRING="" \
 -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG -O3" \
```

**Comment by prudhomm** [comment]
@Trophime somehow the deb tools manage to override the flags and add -g -O2
see here: https://buildkite.com/feelpp/pkg-feelpp-focal/builds/94#_

**Comment by Trophime** [comment]
In my experience, it works see the attached debian/rules
[rules.log](https://github.com/feelpp/feelpp.pkg/files/4353961/rules.log)

**Comment by Trophime** [comment]
NB: I had to rename d/rules to upload it

**Comment by prudhomm** [comment]
you cannot do a PR?
simply edit the file from github and propose the PR

**Comment by Trophime** [comment]
NB it would work only for feelpp package. Check it first then I would take care of feelpp-toolboxes

**Comment by prudhomm** [comment]
I understand now the problem and how to fix it
