### ISSUE TITLE
Missing hearders for mmg in libfeel-dev?

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp.pkg#4]
I think there are missing headers for mmg:
see `feelpp/feel/feelmesh/remesh.hpp:#include <mmg/libmmg.h>`

The problem arises when building toolboxes.

**Comment by prudhomm** [comment]
I forgot to add them in the .install

**Comment by Trophime** [comment]
There are installed in /usr/include not /usr/include/feelpp as the others...

**Comment by prudhomm** [comment]
the deb packages will be available this morning
