### ISSUE TITLE
llvm-13-linker-tools is only available for  ppc64el arch

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp.pkg#7]
For the record, the jammy debian/control need some changes.
llvm-13-linker-tools is only available for  ppc64el arch.

see: https://github.com/feelpp/feelpp.pkg/blob/589c24f6d6641de955ddb4ac736bae7f055f5708/feelpp/jammy/debian/control#L8

**Comment by prudhomm** [comment]
@Trophime it works fine here, see image. The packages are building properly

<img width="714" alt="Screenshot 2022-07-06 at 22 25 08" src="https://user-images.githubusercontent.com/151693/177636757-d0bdb40b-183d-4141-b793-54b8d99f08ff.png">

**Comment by Trophime** [comment]
ok my bad. I close the issue
